### ISSUE TITLE
llvm-config error

### ISSUE THREAD

**Issue by lucwl** [luc-tielen/llvm-codegen#22]
I have installed LLVM 17 on my system, but when I try and build my project with the library I get the following error from setup.exe :

```
Error: setup.exe: 'C:\Program Files\LLVM\bin\llvm-config.exe' exited with an
error:
llvm-config: error: LLVM-17git.dll is missing
```

I have tried LLVM installations from different sources but can't get this to work. Any ideas?

**Comment by luc-tielen** [comment]
Hey @luc-wallace 👋.

I haven't used windows in years but check  the following things:
- is that dll somewhere on your system (it should be after installing llvm17)
- is the directory the dll is in on your "$PATH" (idk what it's called in windows anymore 😅). Add it to the system path if not and try running the command again.

Try those things first, if those are both ok, then it's something in the Setup.hs of this repo that we need to change. Let me know how it goes!

**Comment by lucwl** [comment]
Ended up switching to Linux 😅
I tried several LLVM distributions but couldn't find this DLL file, bizarre.

**Comment by luc-tielen** [comment]
@luc-wallace Sorry to hear that. Is it working for you in Linux now? Can I close this issue?

**Comment by lucwl** [comment]
Yes, all working now thanks! Windows is a joke anyway...
