### ISSUE TITLE
[QUESTION] llvm-codegen for Accelerate

### ISSUE THREAD

**Issue by npatsakula** [luc-tielen/llvm-codegen#3]
Hello @luc-tielen! Is it theoretically possible to replace `llvm-hs` with `llvm-codegen` in Accelerate project?

**Comment by luc-tielen** [comment]
Yes, theoretically it is possible. But keep in mind that so far I only added the functionality I needed for [eclair](https://github.com/luc-tielen/eclair-lang/projects/1).

Should be fairly straight-forward to extend for new instructions though.
